/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DbFile - Filename of current DB
type DbFile struct {

	// filename of db file
	Filename string `json:"filename"`
}

// AssertDbFileRequired checks if the required fields are not zero-ed
func AssertDbFileRequired(obj DbFile) error {
	elements := map[string]interface{}{
		"filename": obj.Filename,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDbFileRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DbFile (e.g. [][]DbFile), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDbFileRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDbFile, ok := obj.(DbFile)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDbFileRequired(aDbFile)
	})
}
