/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Schedule - Holds all data of a generated schedule.
type Schedule struct {

	// The fairness score of this schedule.
	FairnessScore float32 `json:"fairness_score"`

	// The balance score of this schedule.
	BalanceScore float32 `json:"balance_score"`

	// The fairness score for the JAEV shifts of this schedule.
	JaevFairnessScore float32 `json:"jaev_fairness_score"`

	// The balance score for the JAEV shifts of this schedule.
	JaevBalanceScore float32 `json:"jaev_balance_score"`

	// The coverage score of this schedule.
	Coverage float32 `json:"Coverage"`

	// The balance score of this schedule.
	Balance float32 `json:"Balance"`

	// The fairness score.
	Fairness float32 `json:"Fairness"`

	// The total number of shifts that should be assigned.
	TotalNbShifts float32 `json:"TotalNbShifts"`

	// The total number of shifts that are assigned.
	TotalNbShiftsAssigned float32 `json:"TotalNbShiftsAssigned"`

	IndividualSchedules []IndividualSchedule `json:"individual_schedules,omitempty"`
}

// AssertScheduleRequired checks if the required fields are not zero-ed
func AssertScheduleRequired(obj Schedule) error {
	elements := map[string]interface{}{
		"fairness_score": obj.FairnessScore,
		"balance_score": obj.BalanceScore,
		"jaev_fairness_score": obj.JaevFairnessScore,
		"jaev_balance_score": obj.JaevBalanceScore,
		"Coverage": obj.Coverage,
		"Balance": obj.Balance,
		"Fairness": obj.Fairness,
		"TotalNbShifts": obj.TotalNbShifts,
		"TotalNbShiftsAssigned": obj.TotalNbShiftsAssigned,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.IndividualSchedules {
		if err := AssertIndividualScheduleRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseScheduleRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Schedule (e.g. [][]Schedule), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseScheduleRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSchedule, ok := obj.(Schedule)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertScheduleRequired(aSchedule)
	})
}
