openapi: 3.0.0
info:
  description: Basic API for retrieving schedules, based on a ScheduleInput object.
  title: Scheduler API
  version: 0.0.1
servers:
- url: http://localhost:8080
paths:
  /schedule:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
          description: A schedule.
      summary: Returns a generated schedule.
  /model-parameters/get:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelParameters'
          description: The model parameters.
      summary: Returns the current model parameters.
  /model-parameters/set:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelParameters'
        description: The model parameters to be set.
        required: true
      responses:
        "204":
          description: parameters updated in backend
      summary: Sets the model paramters in the backend.
components:
  schemas:
    Schedule:
      description: Holds all data of a generated schedule.
      example:
        nb_days: 1
        individual_schedules:
        - assistant_id: 2
          assignments:
          - part_of_min_balance: true
          - part_of_min_balance: true
        - assistant_id: 2
          assignments:
          - part_of_min_balance: true
          - part_of_min_balance: true
        assistants:
        - id: 5
        - id: 5
        fairness_score: 0.8008281904610115
        balance_score: 6
        shift_types:
        - fairness_score: 5.637376656633329
        - fairness_score: 5.637376656633329
      properties:
        fairness_score:
          description: The fairness score of this schedule
          type: number
        balance_score:
          description: The balance score of this schedule
          type: integer
        nb_days:
          description: The number of days for which this schedule is generated.
          type: integer
        assistants:
          description: The assistants involved in this schedule.
          items:
            $ref: '#/components/schemas/Assistant'
          type: array
        shift_types:
          description: The shift_types that were considered when generating this schedule.
          items:
            $ref: '#/components/schemas/Schedule_shift_types'
          type: array
        individual_schedules:
          items:
            $ref: '#/components/schemas/IndividualSchedule'
          type: array
      type: object
    Assistant:
      description: Represents an assistant.
      example:
        id: 5
      properties:
        id:
          description: The identification number of this assistant.
          type: integer
        type:
          $ref: '#/components/schemas/AssistantType'
        highest_unfair_workload:
          $ref: '#/components/schemas/ShiftType'
        lowest_unfair_workload:
          $ref: '#/components/schemas/ShiftType'
      type: object
    IndividualSchedule:
      description: Represents the work schedule of an individual assistant.
      example:
        assistant_id: 2
        assignments:
        - part_of_min_balance: true
        - part_of_min_balance: true
      properties:
        assistant_id:
          description: The identification number of the assistant for which this is
            an individual schedule.
          type: integer
        assignments:
          description: An array as long as the number of days of this schedule. Contains
            all the assignments that have been scheduled to this assistant.
          items:
            $ref: '#/components/schemas/Assignment'
          type: array
      type: object
    Assignment:
      description: Represents a single shift assignment.
      example:
        part_of_min_balance: true
      properties:
        shift_type:
          $ref: '#/components/schemas/ShiftType'
        part_of_min_balance:
          description: whether or not this assignlent is part of a min balance free
            block.
          type: boolean
      required:
      - part_of_min_balance
      - shift_type
      type: object
    AssistantType:
      description: The different assistant types.
      enum:
      - JA
      - JA_F
      - SA
      - SA_F
      - SA_NEO
      - SA_F_NEO
      type: string
    ShiftType:
      description: The different shift types that can be scheduled, including the
        free shift.
      enum:
      - JAEV
      - JAWH
      - JANW
      - SAEW
      - SAWH
      - TSPT
      - CALL
      - FREE
      type: string
    ModelParameters:
      description: Holds all model parameters to generate a schedule.
      example:
        balance_minimum: 0
        shift_type_params:
        - included_in_balance: true
          fairness_weight: 6.027456183070403
        - included_in_balance: true
          fairness_weight: 6.027456183070403
      properties:
        balance_minimum:
          description: The minimal balance score for an acceptable solution
          type: integer
        shift_type_params:
          items:
            $ref: '#/components/schemas/ShiftTypeModelParameters'
          type: array
      type: object
    ShiftTypeModelParameters:
      description: Holds the shift type specific model parameters.
      example:
        included_in_balance: true
        fairness_weight: 6.027456183070403
      properties:
        shift_type:
          $ref: '#/components/schemas/ShiftType'
        fairness_weight:
          description: The weight of this shift type in the fairness score.
          type: number
        included_in_balance:
          description: Whether or not this shift type is included when computing the
            balaance score.
          type: boolean
      type: object
    Schedule_shift_types:
      example:
        fairness_score: 5.637376656633329
      properties:
        fairness_score:
          description: The fairness score for this shift type
          type: number
        shift_type:
          $ref: '#/components/schemas/ShiftType'
      type: object
