openapi: 3.0.0
info:
  title: Scheduler API
  description: Basic API for retrieving schedules, based on a ScheduleInput object.
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /schedule:
    get:
      summary: Returns a generated schedule.
      responses:
        '200':
          description: A schedule.
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Schedule"
                

components:
  schemas:
    Schedule:
      type: object
      description: Holds all data of a generated schedule.
      properties:
        nb_days: 
          type: integer
          description: The number of days for which this schedule is generated.
        assistants: 
          description: The assistants involved in this schedule.
          type: array
          items:
            $ref: "#/components/schemas/Assistant"
        shift_types:
            $ref: "#/components/schemas/ShiftType"
        individual_schedules: 
            type: array
            items:
              $ref: "#/components/schemas/IndividualSchedule"
          

    Assistant:
      type: object
      description: Represents an assistant.
      properties:
        id:
          type: integer
          description: The identification number of this assistant.
        type:
          $ref: "#/components/schemas/AssistantType"

        
    IndividualSchedule:
      type: object
      description: Represents the work schedule of an individual assistant.
      properties:
        assistant_id: 
          type: integer
          description: The identification number of the assistant for which this is an individual schedule.
        assignments:
          type: array
          description: An array as long as the number of days of this schedule. Contains all the assignments that have been scheduled to this assistant.
          items: 
            $ref: "#/components/schemas/ShiftType"
    
    AssistantType:
      type: string
      description: The different assistant types.
      enum:
        - JA
        - JA_F
        - SA
        - SA_F
        - SA_NEO
        - SA_F_NEO
    
        
    ShiftType:
      type: string
      description: The different shift types that can be scheduled, including the free shift.
      enum:
        - JA_E
        - JA_WH
        - JA_NW
        - SA_EW
        - SA_WH
        - TS
        - C
        - F  