openapi: 3.0.0
info:
  title: Scheduler API
  description: Basic API for retrieving schedules, based on a ScheduleInput object.
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /schedule:
    get:
      summary: Returns a generated schedule.
      responses:
        '200':
          description: A schedule.
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Schedule"
  /model-parameters/get:
    get:
      summary: Returns the current model parameters.
      responses:
        '200':
          description: The model parameters.
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ModelParameters"
  /model-parameters/set:
    post:
      summary: Sets the model paramters in the backend.
      requestBody:
        description: The model parameters to be set.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModelParameters"
      responses:
        '204':
          description: "parameters updated in backend"
                  
components:
  schemas:
    Schedule:
      type: object
      description: Holds all data of a generated schedule.
      properties:
        fairness_score:
          type: number
          description: The fairness score of this schedule
        balance_score:
          type: integer
          description: The balance score of this schedule
        nb_days: 
          type: integer
          description: The number of days for which this schedule is generated.
        assistants: 
          description: The assistants involved in this schedule.
          type: array
          items:
            $ref: "#/components/schemas/Assistant"
        shift_types:
            description: The shift_types that were considered when generating this schedule.
            type: array
            items:
              type: object
              properties:
                fairness_score:
                  type: number
                  description: The fairness score for this shift type
                shift_type:
                  $ref: "#/components/schemas/ShiftType"
        individual_schedules: 
            type: array
            items:
              $ref: "#/components/schemas/IndividualSchedule"
    Assistant:
      type: object
      description: Represents an assistant.
      properties:
        id:
          type: integer
          description: The identification number of this assistant.
        type:
          $ref: "#/components/schemas/AssistantType"
        highest_unfair_workload:
          $ref: "#/components/schemas/ShiftType"
        lowest_unfair_workload:
          $ref: "#/components/schemas/ShiftType"
    IndividualSchedule:
      type: object
      description: Represents the work schedule of an individual assistant.
      properties:
        assistant_id: 
          type: integer
          description: The identification number of the assistant for which this is an individual schedule.
        assignments:
          type: array
          description: An array as long as the number of days of this schedule. Contains all the assignments that have been scheduled to this assistant.
          items: 
            $ref: "#/components/schemas/Assignment"
    Assignment:
      type: object
      description: Represents a single shift assignment.
      required:
        - shift_type
        - part_of_min_balance
      properties:
        shift_type:
          $ref: "#/components/schemas/ShiftType"
        part_of_min_balance:
          type: boolean
          description: whether or not this assignlent is part of a min balance free block.
    AssistantType:
      type: string
      description: The different assistant types.
      enum:
        - JA
        - JA_F
        - SA
        - SA_F
        - SA_NEO
        - SA_F_NEO  
    ShiftType:
      type: string
      description: The different shift types that can be scheduled, including the free shift.
      enum:
        - JAEV
        - JAWH
        - JANW
        - SAEW
        - SAWH
        - TSPT
        - CALL
        - FREE  
    ModelParameters: 
      type: object
      description: Holds all model parameters to generate a schedule.
      properties:
        balance_minimum:
          type: integer
          description: The minimal balance score for an acceptable solution
        shift_type_params:
          type: array 
          items:
            $ref: "#/components/schemas/ShiftTypeModelParameters"
          
    ShiftTypeModelParameters:
      description: Holds the shift type specific model parameters.
      type: object
      properties:
        shift_type:
          $ref: "#/components/schemas/ShiftType"
        fairness_weight:
          type: number
          description: The weight of this shift type in the fairness score.
        included_in_balance:
          type: boolean
          description: Whether or not this shift type is included when computing the balaance score.