openapi: 3.0.0
info:
  title: Scheduler API
  description: Basic API for retrieving schedules, based on a ScheduleInput object.
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /schedule:
    get:
      summary: Returns a generated schedule.
      responses:
        '200':
          description: A schedule.
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Schedule"
  /model-parameters/get:
    get:
      summary: Returns the current model parameters.
      responses:
        '200':
          description: Succesful operation.
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ModelParameters"
  /model-parameters/set:
    post:
      summary: Sets the model paramters in the backend.
      requestBody:
        description: The model parameters to be set.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModelParameters"
      responses:
        '204':
          description: Model parameters succesfully updated in backend.
  /instance-data/get:
    get:
      summary: Returns the current instance data.
      responses: 
        '200':
          description: Succesful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InstanceData"
  /instance-data/set:
    post:
      summary: Sets the insatnce data in the backend.
      requestBody:
        description: The instance data to be set.
        required: true
        content:
          application/json:
            schema:
             $ref: "#/components/schemas/InstanceData"
      responses:
        '204':
          description: Instance data succesfully updated in backend.
              
        
          
                  
components:
  schemas:
    Schedule:
      type: object
      description: Holds all data of a generated schedule.
      required:
        - holidays
        - jaev_fairness_score
        - fairness_score
      properties:
        fairness_score:
          type: number
          description: The fairness score of this schedule
        balance_score:
          type: integer
          description: The balance score of this schedule
        jaev_fairness_score:
          type: number
          description: The fairness score for teh JAEV schedule
        jaev_balance:
          type: integer
          description: The balance for the JAEV schedule
        nb_days: 
          type: integer
          description: The number of days for which this schedule is generated.
        holidays:
          type: array
          items:
            type: integer
        assistants: 
          description: The assistants involved in this schedule.
          type: array
          items:
            $ref: "#/components/schemas/Assistant"
        shift_types:
            description: The shift types that were considered when generating this schedule.
            type: array
            items:
              $ref: "#/components/schemas/ShiftType"
        individual_schedules: 
            type: array
            items:
              $ref: "#/components/schemas/IndividualSchedule"
    Assistant:
      type: object
      description: Represents an assistant.
      required:
        - id
        - type
        - workload
      properties:
        id:
          type: integer
          description: The identification number of this assistant.
        type:
          $ref: "#/components/schemas/AssistantType"
        workload:
          type: number
          description: The workload on this assiastant in the schedule.
    IndividualSchedule:
      type: object
      description: Represents the work schedule of an individual assistant.
      properties:
        assistant_id: 
          type: integer
          description: The identification number of the assistant for which this is an individual schedule.
        assignments:
          type: array
          description: An array as long as the number of days of this schedule. Contains all the assignments that have been scheduled to this assistant.
          items: 
            $ref: "#/components/schemas/Assignment"
    Assignment:
      type: object
      description: Represents a single shift assignment.
      required:
        - shift_type
        - part_of_min_balance
      properties:
        shift_type:
          $ref: "#/components/schemas/ShiftType"
        part_of_min_balance:
          type: boolean
          description: whether or not this assignment is part of a min balance free block.
    AssistantType:
      type: string
      description: The different assistant types.
      enum:
        - JA
        - JA_F
        - SA
        - SA_F
        - SA_NEO
        - SA_F_NEO  
    ShiftType:
      type: string
      description: The different shift types that can be scheduled, including the free shift.
      enum:
        - JAEV
        - JAWH
        - JANW
        - SAEW
        - SAWH
        - TSPT
        - CALL
        - FREE  
    ModelParameters: 
      type: object
      description: Holds all model parameters to generate a schedule.
      properties:
        balance_minimum:
          type: integer
          description: The minimal balance score for an acceptable solution.
        balance_minimun_jaev:
          type: integer
          description: The mininmal balance score for JAEV shifts for an acceptable solution.
        shift_type_params:
          type: array 
          items:
            $ref: "#/components/schemas/ShiftTypeModelParameters"
    ShiftTypeModelParameters:
      description: Holds the shift type specific model parameters.
      type: object
      required:
        - shift_type
        - shift_workload
        - max_buffer
      properties:
        shift_type:
          $ref: "#/components/schemas/ShiftType"
        shift_workload:
          type: number
          description: The weight of this shift type in the fairness score.
        max_buffer:
          type: integer
          description: The number of assignments per assisant allowed above the minimun for this shift type. 
    InstanceData:
      description:  Holds the instance data for scheduling.
      type: object
      required:
        - assistants
        - nb_weeks
        - holidays
      properties:
        assistants:
          type: array
          items:
            $ref: "#/components/schemas/AssistantInstance"
        nb_weeks:
          type: integer
          description: The number of weeks to be scheduled in this instance
        holidays:
          type: array
          items:
            type: integer
    AssistantInstance:
      description: Holds all instance data for one assistant.
      type: object
      required:
        - id
        - name
        - type
        - free_days
      properties:
        id:
          type: integer
          description: The identification number of this assistant.
        name:
          type: string
          description: The name of this assistant.
        type:
          $ref: "#/components/schemas/AssistantType"
        free_days:
          type: array
          description: The free days granted to this assistant for the current scheduling period.
          items:
            type: integer
          