/*
 * Scheduler API
 *
 * Basic API for retrieving schedules, based on a ScheduleInput object.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/DennisMaes6/scheduler/backend/server"
	//"github.com/gorilla/handlers"
	"github.com/rs/cors"
)

func main() {
	log.Printf("Server started")
	//handlers.AllowedOrigins([]string{"*"})

	DefaultApiService := openapi.NewDefaultApiService()
	DefaultApiController := openapi.NewDefaultApiController(DefaultApiService)
	

	router := openapi.NewRouter(DefaultApiController)

	c := cors.New(cors.Options{
		AllowedMethods:   []string{"POST", "GET", "PUT", "OPTIONS"},
		//AllowedHeaders:   []string{"content-type"},
		//AllowCredentials: true,
	})

	handler := c.Handler(router)

	log.Fatal(http.ListenAndServe(":8080", handler))

}
