/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// DbScheduleGet - Returns the schedule as found in the db.
func (s *DefaultApiService) DbScheduleGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update DbScheduleGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Schedule{}) or use other options such as http.Ok ...
	//return Response(200, Schedule{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DbScheduleGet method not implemented")
}

// FileScheduleGet - Returns the schedule as found in a file.
func (s *DefaultApiService) FileScheduleGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update FileScheduleGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Schedule{}) or use other options such as http.Ok ...
	//return Response(200, Schedule{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("FileScheduleGet method not implemented")
}

// InstanceDataGetGet - Returns the current instance data.
func (s *DefaultApiService) InstanceDataGetGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update InstanceDataGetGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InstanceData{}) or use other options such as http.Ok ...
	//return Response(200, InstanceData{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("InstanceDataGetGet method not implemented")
}

// InstanceDataSetPost - Sets the insatnce data in the backend.
func (s *DefaultApiService) InstanceDataSetPost(ctx context.Context, instanceData InstanceData) (ImplResponse, error) {
	// TODO - update InstanceDataSetPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("InstanceDataSetPost method not implemented")
}

// ModelParametersGetGet - Returns the current model parameters.
func (s *DefaultApiService) ModelParametersGetGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ModelParametersGetGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ModelParameters{}) or use other options such as http.Ok ...
	//return Response(200, ModelParameters{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ModelParametersGetGet method not implemented")
}

// ModelParametersSetPost - Sets the model paramters in the backend.
func (s *DefaultApiService) ModelParametersSetPost(ctx context.Context, modelParameters ModelParameters) (ImplResponse, error) {
	// TODO - update ModelParametersSetPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ModelParametersSetPost method not implemented")
}

// ScheduleFileSetPost - Sets the schedule DB file in the backend.
func (s *DefaultApiService) ScheduleFileSetPost(ctx context.Context, dbFile DbFile) (ImplResponse, error) {
	// TODO - update ScheduleFileSetPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ScheduleFileSetPost method not implemented")
}

// ScheduleGenerateGet - Returns a schedule generated with Java.
func (s *DefaultApiService) ScheduleGenerateGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ScheduleGenerateGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Schedule{}) or use other options such as http.Ok ...
	//return Response(200, Schedule{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ScheduleGenerateGet method not implemented")
}

// ScheduleGet - Returns a schedule generated with MiniZinc.
func (s *DefaultApiService) ScheduleGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ScheduleGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Schedule{}) or use other options such as http.Ok ...
	//return Response(200, Schedule{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ScheduleGet method not implemented")
}
