/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ModelParameters - Holds all model parameters for generating schedules.
type ModelParameters struct {

	// The minimal balance score for an acceptable solution.
	MinBalance int32 `json:"min_balance,omitempty"`

	// The mininmal balance score for JAEV shifts for an acceptable solution.
	MinBalanceJaev int32 `json:"min_balance_jaev,omitempty"`

	ShiftTypeParameters []ShiftTypeModelParameters `json:"shift_type_parameters,omitempty"`
}

// AssertModelParametersRequired checks if the required fields are not zero-ed
func AssertModelParametersRequired(obj ModelParameters) error {
	for _, el := range obj.ShiftTypeParameters {
		if err := AssertShiftTypeModelParametersRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseModelParametersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ModelParameters (e.g. [][]ModelParameters), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseModelParametersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aModelParameters, ok := obj.(ModelParameters)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertModelParametersRequired(aModelParameters)
	})
}
