/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// AssistantType : The skill category of an assistant.
type AssistantType string

// List of AssistantType
const (
	JA       AssistantType = "JA"
	JA_F     AssistantType = "JA_F"
	SA       AssistantType = "SA"
	SA_F     AssistantType = "SA_F"
	SA_NEO   AssistantType = "SA_NEO"
	SA_F_NEO AssistantType = "SA_F_NEO"
)
