/*
 * Scheduler API
 *
 * Basic API for retrieving schedules, based on a ScheduleInput object.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// AssistantInstance - Holds all instance data for one assistant.
type AssistantInstance struct {

	// The identification number of this assistant.
	Id int32 `json:"id"`

	// The name of this assistant.
	Name string `json:"name"`

	Type AssistantType `json:"type"`

	// The free days granted to this assistant for the current scheduling period.
	FreeDays []int32 `json:"free_days"`
}
