/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// Schedule - Holds all data of a generated schedule.
type Schedule struct {

	// The fairness score of this schedule.
	FairnessScore float32 `json:"fairness_score"`

	// The balance score of this schedule.
	BalanceScore float32 `json:"balance_score"`

	// The fairness score for the JAEV shifts of this schedule.
	JaevFairnessScore float32 `json:"jaev_fairness_score"`

	// The balance score for the JAEV shifts of this schedule.
	JaevBalanceScore float32 `json:"jaev_balance_score"`

	IndividualSchedules []IndividualSchedule `json:"individual_schedules,omitempty"`
}
