/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ShiftType : Identifies a specific shift type. Includes the FREE shift type.
type ShiftType string

// List of ShiftType
const (
	JAEV  ShiftType = "JAEV"
	JAWE  ShiftType = "JAWE"
	JAHO  ShiftType = "JAHO"
	SANW  ShiftType = "SANW"
	SAEW  ShiftType = "SAEW"
	SAWE  ShiftType = "SAWE"
	SAHO  ShiftType = "SAHO"
	SAEV1 ShiftType = "SAEV1"
	SAEV2 ShiftType = "SAEV2"
	TPWE  ShiftType = "TPWE"
	TPHO  ShiftType = "TPHO"
	TPNF  ShiftType = "TPNF"
	CALL  ShiftType = "CALL"
	FREE  ShiftType = "FREE"
)
