/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// IndividualSchedule - Represents the work schedule of an individual assistant.
type IndividualSchedule struct {

	// The identification number of the assistant for which this is an individual schedule.
	AssistantId int32 `json:"assistant_id"`

	// The workload of this inidividual schedule. Used when calculating the fairness score.
	Workload float32 `json:"workload"`

	// Contains all the individual assignments of this individual schedule.
	Assignments []Assignment `json:"assignments"`
}
