/*
 * Scheduler API
 *
 * Basic API for retrieving schedules, based on a ScheduleInput object.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type ScheduleShiftTypes struct {

	// The fairness score for this shift type
	FairnessScore float32 `json:"fairness_score,omitempty"`

	ShiftType ShiftType `json:"shift_type,omitempty"`
}
