/*
 * Scheduler API
 *
 * Basic API for retrieving schedules, based on a ScheduleInput object.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ShiftType : The different shift types that can be scheduled, including the free shift.
type ShiftType string

// List of ShiftType
const (
	JA_E  ShiftType = "JA_E"
	JA_WH ShiftType = "JA_WH"
	JA_NW ShiftType = "JA_NW"
	SA_EW ShiftType = "SA_EW"
	SA_WH ShiftType = "SA_WH"
	TS    ShiftType = "TS"
	C     ShiftType = "C"
	F     ShiftType = "F"
)
