/*
 * Scheduler API
 *
 * Basic API for retrieving schedules, based on a ScheduleInput object.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// Assignment - Represents a single shift assignment.
type Assignment struct {
	ShiftType ShiftType `json:"shift_type"`

	// whether or not this assignlent is part of a min balance free block.
	PartOfMinBalance bool `json:"part_of_min_balance"`
}
