/*
 * Scheduler API
 *
 * Basic API for retrieving schedules, based on a ScheduleInput object.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ShiftType : The different shift types that can be scheduled, including the free shift.
type ShiftType string

// List of ShiftType
const (
	JAEV ShiftType = "JAEV"
	JAWH ShiftType = "JAWH"
	JANW ShiftType = "JANW"
	SAEW ShiftType = "SAEW"
	SAWH ShiftType = "SAWH"
	TSPT ShiftType = "TSPT"
	CALL ShiftType = "CALL"
	FREE ShiftType = "FREE"
)
