/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// IndividualSchedule - Represents the work schedule of an individual assistant.
type IndividualSchedule struct {

	// The identification number of the assistant for which this is an individual schedule.
	AssistantId int32 `json:"assistant_id"`

	// The workload of this inidividual schedule. Used when calculating the fairness score.
	Workload float32 `json:"workload"`

	// Contains all the individual assignments of this individual schedule.
	Assignments []Assignment `json:"assignments"`

	// Sum of all shifts with their weights
	AbsoluteWorkload float32 `json:"absolute_workload,omitempty"`

	// Total days available
	DaysAvailable int32 `json:"days_available,omitempty"`

	// Total days worked
	DaysWorked int32 `json:"days_worked,omitempty"`

	// Total days vacation
	DaysVacation int32 `json:"days_vacation,omitempty"`

	// Average days rest between 2 shifts
	AvgDaysRest float32 `json:"avg_days_rest,omitempty"`
}
