/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// DayDate - Represents the date of this day.
type DayDate struct {

	// The day of month of this day.
	Day int32 `json:"day"`

	// The month of this day. 1 = January, 12 = December
	Month int32 `json:"month"`

	// The year of this day.
	Year int32 `json:"year"`
}
