/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// Assignment - Represents a single shift assignment.
type Assignment struct {

	// The day of the scheduling period for which this is an assignment.
	DayNb int32 `json:"day_nb"`

	ShiftType ShiftType `json:"shift_type"`

	// Indicates whether or not this assignment is part of a streak of free days as long as the min_balance score for this schedule.
	PartOfMinBalance bool `json:"part_of_min_balance"`
}
