/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// Day - Represents a single day in the scheduling period.
type Day struct {

	// The day number of this day in the current scheduling period.
	Id int32 `json:"id"`

	// A string representation of the date that is represented by this day.
	Date string `json:"date"`

	// Indicates whether or not this day should be considered a holiday in the produced schedule.
	IsHoliday bool `json:"is_holiday"`
}
