/*
 * Scheduler API
 *
 * Basic API for retrieving schedules, based on a ScheduleInput object.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// Assistant - Represents an assistant.
type Assistant struct {

	// The identification number of this assistant.
	Id int32 `json:"id,omitempty"`

	Type AssistantType `json:"type,omitempty"`

	// Indicates that this assistant has the highest workload for the most unfair shift.
	HighestUnfairWorkload bool `json:"highest_unfair_workload,omitempty"`

	// Indicates that this assistant has the highest workload for the most unfair shift.
	LowestUnfairWorkload bool `json:"lowest_unfair_workload,omitempty"`
}
