/*
 * Scheduler API
 *
 * Basic API for retrieving schedules, based on a ScheduleInput object.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// Assistant - Represents an assistant.
type Assistant struct {

	// The identification number of this assistant.
	Id int32 `json:"id"`

	Type AssistantType `json:"type"`

	HighestUnfairWorkload []ShiftType `json:"highest_unfair_workload"`

	LowestUnfairWorkload []ShiftType `json:"lowest_unfair_workload"`
}
