/*
 * Scheduler API
 *
 * Basic API for retrieving schedules, based on a ScheduleInput object.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ShiftTypeModelParameters - Holds the shift type specific model parameters.
type ShiftTypeModelParameters struct {
	ShiftType ShiftType `json:"shift_type,omitempty"`

	// The weight of this shift type in the fairness score.
	FairnessWeight float32 `json:"fairness_weight,omitempty"`

	// Whether or not this shift type is included when computing the balaance score.
	IncludedInBalance bool `json:"included_in_balance,omitempty"`
}
