/*
 * Scheduler API
 *
 * API for getting generated schedules. Also used for getting and setting model parameters and instance data.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ShiftTypeModelParameters - Holds the shift type specific model parameters.
type WeightModelParameters struct {
	Coverage float32 `json:"coverage"`

	// The weight of this shift type in the fairness score.
	Balance float32 `json:"balance"`

	// The amount of personnel needed for this particular shift.
	Fairness float32 `json:"fairness"`
}
